#+Title: Efforts on fix and host Linux lab
#+Date: <2016-05-13 Fri>
#+Author: Yogesh Agrawal
#+Email: yogesh@vlabs.ac.in

* Introduction
  This document describes the efforts that are done to fix and host
  Linux Lab.

* Provisioning of servers
  Create following containers in base4:
  - template :: ubuntu-12.04-custom-x86_64

** Linux Lab
   1. Set proxy in ~/.bashrc file.
   2. Update the system.
      #+BEGIN_EXAMPLE
      apt-get update
      #+END_EXAMPLE
   3. Clone the lab source code.
      #+BEGIN_EXAMPLE
      git clone https://github.com/Virtual-Labs/linux-lab-iiith.git
      #+END_EXAMPLE
   4. Install graphviz and php.
      #+BEGIN_EXAMPLE
      apt-get install graphviz php5
      #+END_EXAMPLE
   5. Navigate to src folder and execute make command.
   6. Rsync the content of build folder to =/var/www= directory.
   7. Navigate to http://10.4.15.214/ to view the lab.
   8. Install ldapscripts
      #+BEGIN_EXAMPLE
      apt-get install ldapscripts
      #+END_EXAMPLE
      - refer :: http://www.meso.northwestern.edu/intranet/recipies/useful-computer-files-and-programs/configuring-group-linux-servers-and-terminals-with-ldap-kerberos-and-nfs/ldap-user-and-group-management		  
   9. Configure =/etc/ldapscripts/ldapscripts.conf= as follows:
      #+BEGIN_EXAMPLE
      SERVER=localhost
      BINDDN='cn=admin,dc=example,dc=com'
      BINDPWDFILE="/etc/ldapscripts/ldapscripts.passwd"
      SUFFIX='dc=example,dc=com'
      GSUFFIX='ou=Group'
      USUFFIX='ou=People'
      MSUFFIX='ou=Computers'
      GIDSTART=10000
      UIDSTART=10000
      MIDSTART=10000
      #+END_EXAMPLE
   10. Create =ldapscripts.passwd= file as follows:
       #+BEGIN_EXAMPLE
       sudo sh -c "echo -n 'password' > /etc/ldapscripts/ldapscripts.passwd"
       sudo chmod 400 /etc/ldapscripts/ldapscripts.passwd
       #+END_EXAMPLE
   11. Set ip address and password of ldap server in
       /var/www/php/ldapexec.php file.
   12. Now when we try to register the user
       http://10.4.15.214/php/register-form.php it throws following
       error:
       #+BEGIN_EXAMPLE
       Oops! Some error occurred.
       Failed to create user: Could not guess current userUnable to create /var/log/ldapscripts.log, exiting...
       #+END_EXAMPLE
       After doing below troubleshooting steps registration is working
       properly.
       - Troubleshooting ::
         1. Set =USER= directive in =/usr/share/ldapscripts/runtime=
            as follows:
            #+BEGIN_EXAMPLE
            USER=$(whoami 2>/dev/null)
            #+END_EXAMPLE
            Because =logname= does not work.
            #+BEGIN_EXAMPLE
            $ logname
            logname: no login name
            #+END_EXAMPLE
	    - refer:
              http://stackoverflow.com/questions/18017311/bash-script-using-ldapscripts-package-does-not-work-from-cron
         2. Grant read privileges to ldapscripts.passwd file.
            #+BEGIN_EXAMPLE
            chmod 440 ldapscripts.passwd
            #+END_EXAMPLE
         3. Add =www-data= user to =root= group and restart apache
            service so that it can read the password file.
            #+BEGIN_EXAMPLE
            usermod -a -G root www-data
            service apache2 restart
            #+END_EXAMPLE
		   
** GateOne server
*** Approach 1 (Not working)
   - refer: https://www.digitalocean.com/community/tutorials/how-to-ssh-into-your-vps-from-the-browser-with-gateone
   1. set proxy
   2. apt-get update
   3. apt-get install curl
   4. Download gateone
      #+BEGIN_EXAMPLE
      curl -L http://github.com/liftoff/GateOne/archive/master.tar.gz > ~/gateone.tar.gz
      #+END_EXAMPLE
   5. Extract
      #+BEGIN_EXAMPLE
      tar xvzf ~/gateone.tar.gz -C ~
      #+END_EXAMPLE
   6. Install python libraries
      #+BEGIN_EXAMPLE
      apt-get install python-pip debhelper python-support -y
      #+END_EXAMPLE
   7. Use pip to install extra packages
      #+BEGIN_EXAMPLE
      pip install tornado stdeb
      #+END_EXAMPLE
   8. Create a deb package for GateOne
      #+BEGIN_EXAMPLE
      cd ~/GateOne-master
      python setup.py --command-packages=stdeb.command bdist_deb
      #+END_EXAMPLE

*** Approach 2 (Working)
    - refer: http://liftoff.github.io/GateOne/About/
    1. install tornado
       #+BEGIN_EXAMPLE
       pip install tornado==2.4.1
       #+END_EXAMPLE
    2. Download gateone from
       https://github.com/downloads/liftoff/GateOne/gateone_1.1-1_all.deb
    3. Install gateone via dpkg
       #+BEGIN_EXAMPLE
       dpkg -i gateone*.deb
       #+END_EXAMPLE
    4. Navigate inside =/opt/gateone= directory, and execute
       gateone.py.
       #+BEGIN_EXAMPLE
       ./gateone.py
       #+END_EXAMPLE
    5. Now browse https://10.4.15.215 to access gateone server.
*** Reference
   - https://github.com/liftoff/GateOne/downloads
   - https://www.youtube.com/watch?v=gnVohdlZXVY&list=UU8c7zNWoShUxaFqWKv7H51g&index=3&feature=plpp_video
** Ldap server
   1. set proxy
   2. Update the system.
      #+BEGIN_EXAMPLE
      apt-get update
      #+END_EXAMPLE
   3. Install openldap.
      #+BEGIN_EXAMPLE
      apt-get install slapd ldap-utils
      #+END_EXAMPLE
   4. Reconfigure slapd.
      #+BEGIN_EXAMPLE
      dpkg-reconfigure slapd
      #+END_EXAMPLE
      Use following settings:
      #+BEGIN_EXAMPLE
      Omit OpenLDAP server configuration? No
      DNS domain name: virtual-labs.ac.in
      Organization name? Virtual Labs
      Administrator password: password
      Confirm password: password
      Database backend to use: HDB
      Do you want the database to be removed when slapd is purged? No
      #+END_EXAMPLE
   5. Verify that the ldap setup is done properly.
      #+BEGIN_EXAMPLE
      ldapsearch -Y EXTERNAL -H ldapi:// -b 'dc=virtual-labs,dc=ac,dc=in'
      #+END_EXAMPLE
   6. Create organizational units for people and groups using
      following command:
      #+BEGIN_EXAMPLE
      ldapadd -x -D 'cn=admin,dc=virtual-labs,dc=ac,dc=in' -W -f units.ldif
      #+END_EXAMPLE
      units.ldif file should have following content:
      #+BEGIN_EXAMPLE
      dn: ou=People,dc=virtual-labs,dc=ac,dc=in
      ou: People
      objectClass: organizationalUnit
      dn: ou=Group,dc=virtual-labs,dc=ac,dc=in
      ou: Group
      objectClass: organizationalUnit
      #+END_EXAMPLE
   7. Create a group 'vlusers' for Virtual Labs end users using
      following command:
      #+BEGIN_EXAMPLE
      ldapadd -x -D 'cn=admin,dc=virtual-labs,dc=ac,dc=in' -W -f group.ldif
      #+END_EXAMPLE
      group.ldif should have following content:
      #+BEGIN_EXAMPLE
      dn: cn=vlusers,ou=Group,dc=virtual-labs,dc=ac,dc=in
      cn: vlusers
      gidNumber: 20000
      objectClass: top
      objectClass: posixGroup
      #+END_EXAMPLE
   8. Create a 'testuser' user in 'vlusers' group using following
      command:
      #+BEGIN_EXAMPLE
      ldapadd -x -D 'cn=admin,dc=virtual-labs,dc=ac,dc=in' -W -f testuser1.ldif
      #+END_EXAMPLE
      testuser1.ldif should have following content
      #+BEGIN_EXAMPLE
      dn: uid=testuser1,ou=People,dc=virtual-labs,dc=ac,dc=in
      uid: testuser1
      uidNumber: 20000
      gidNumber: 20000
      cn: Test User 1
      sn: User
      objectClass: top
      objectClass: person
      objectClass: posixAccount
      objectClass: shadowAccount
      loginShell: /bin/bash
      homeDirectory: /home/testuser1
      #+END_EXAMPLE
    
** SSH Server
   1. set proxy
   2. apt-get update
   3. Install libpam-ldapd package
      #+BEGIN_EXAMPLE
      apt-get install libpam-ldapd
      #+END_EXAMPLE
      Answer the following questions:
      #+BEGIN_EXAMPLE
      IP address / hostname of the LDAP server: ldap.virtual-labs.ac.in
      The search base: dc=virutal-labs,dc=ac,dc=in
      Version of the LDAP connecting to: Version 3
      Configuring LIBNSS-LDAP: OK
      Make root the DB admin: Yes
      DB requires logging in: No
      Root account of LDAP: cn=admin,dc=virtual-labs,dc=ac,dc=in
      Root password: password
      #+END_EXAMPLE
   4. Verify that the ldap server is being reached and everything is
      working fine:
      #+BEGIN_EXAMPLE
      getent passwd
      #+END_EXAMPLE
   5. Enable creating home directories when user logs in. Edit
      /etc/pam.d/common-session and add the following line.
     #+BEGIN_EXAMPLE
     session required pam_mkhomedir.so skel=/etc/skel umask=0022
     #+END_EXAMPLE
** Set up NFS server
   To setup nfs server followings steps are done:
   1. set proxy
   2. apt-get update
   3. Install nfs kernel 
      #+BEGIN_EXAMPLE
      mkdir -p /var/export/nfs4/home
      apt-get install nfs-kernel-server -y
      #+END_EXAMPLE
      - status :: Installation fails
		 #+BEGIN_EXAMPLE
		 Creating config file /etc/exports with new version
		 Creating config file /etc/default/nfs-kernel-server with new version
		 * Not starting NFS kernel daemon: no support in current kernel.
		 Processing triggers for libc-bin ...
		 ldconfig deferred processing now taking place
		 #+END_EXAMPLE
   4. Edit /etc/exports and add the following lines, replace
      <ip-address> with the ip of the shell server.
      #+BEGIN_EXAMPLE
      /var/export/nfs4       <ip-address>(rw,sync,no_subtree_check)
      /var/export/nfs4/home  <ip-address>(rw,sync,no_subtree_check)
      #+END_EXAMPLE
   5. Refresh the export list
      #+BEGIN_EXAMPLE
      exports -rav
      #+END_EXAMPLE
      - status :: This command throws an error as command not found.
      #+BEGIN_EXAMPLE
      root@linux-lab-nfs:~# exports -rav
      -su: exports: command not found
      #+END_EXAMPLE

* Reference Links
  - https://github.com/Virtual-Labs/documentation-popl-linux-labs/blob/master/documents/POPL-backend-gateone-ldap.pdf
  - 
